### ISSUE TITLE
Clarification for one of the functions

### ISSUE THREAD

**Issue by nomahen** [rlopezcoto/EDGE#5]
Hi there,
I'm an undergraduate trying to understand and modify the code a little bit.
I have a involving the Flux_all_pulsars() function; when you calculate f_st:
530 > f_st = Q0 * e**-2.4 / (4*gp.pi * D * d) * erfc(d/(2 * np.sqrt(D * t_gamma))) 

All of these values are scalars except for d, t_gamma, which are each 1-D arrays of the same shape. So, when you calculate f_st, you'll be matching d and t_gamma element by element, where I would expect you to calculate each value of d for each value of t_gamma. 

Am I misreading the code or missing something?

Thanks

**Comment by rlopezcoto** [comment]
Hi,
this function is inside a loop over the energies, so for each energy, we calculate f_st (Eq. 21 from Atoyan et al. 1995). _d_ and _t_gamma_ are 1-D arrays with a number of elements equal to the number of pulsars simulated. For each pulsar, we calculate the distance _d_ and the diffusion time _t_gamma_. Note that this would be easier if we just had to multiply it by the age of the pulsar _age_, but this is not possible because the diffusion time for a given energy might be dominated by the cooling time instead of the age (hence the if statement in L524). Hope this helps.

As a side note, the _Flux_Earth_all_pulsars_ function was not intensively tested since it is not used in the Science paper this code was written for: http://science.sciencemag.org/content/358/6365/911
Please report any problem with it.

**Comment by nomahen** [comment]
Hi,
Thanks, this makes a lot more sense, I was misunderstanding then. I'll let you know if I find any problems.

Thank you.
